name: quizzly_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  confetti: ^0.7.0
  avatar_glow: ^2.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.0.5
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
    - family: Expletus Sans
      fonts:
        - asset: assets/fonts/ExpletusSans-Regular.ttf
          weight: 400

flutter_intl:
  enabled: true
